FROM python:3.10.12


ADD docker/sources.list /etc/apt/sources.list

COPY docker/init.sh /init.sh
RUN bash /init.sh

ENV TZ=Asia/Shanghai
ENV LOG_HOME="/logs"
RUN mkdir -p ${LOG_HOME}

ENV AGIT_CONFIG_HOME="/agi-tools/config"
ENV AGIT_ENV="prod"
ENV ZHIPUAI_API_KEY="3aeba2365174e850ba45417a16252a09.6gYmkzwLybkub5EW"


COPY requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn


COPY . /agi-tools
WORKDIR /agi-tools

ENTRYPOINT ["streamlit run app.py --server.port 8501 --logger.level=debug 2>&1 | tee $LOG_HOME/st_tool.log"]